set_property SRC_FILE_INFO {cfile:/home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0_in_context.xdc rfile:../../../../../modulationFm.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0_in_context.xdc id:1 order:EARLY scoped_inst:sin/design_1_i/dds_compiler_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/constrs_1/new/mycontraint.xdc rfile:../../../../../modulationFm.srcs/constrs_1/new/mycontraint.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.runs/synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins sin/design_1_i/dds_compiler_0/aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells sin/design_1_i/dds_compiler_0]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells sin/design_1_i]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells sin/design_1_i/dds_compiler_0]
