set_property SRC_FILE_INFO {cfile:/home/fabrice/Documents/modulationFM/modulationFM.srcs/constrs_1/new/mycontraint.xdc rfile:../../../modulationFM.srcs/constrs_1/new/mycontraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk100M]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk100M]
