# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.cache/wt [current_project]
set_property parent.project_path /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/fabrice/Documents/ethOverOfdm/fpga/afficheur2/afficheur2.srcs/sources_1/new/bcd.v
  /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/new/counter.v
  /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
  /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/new/pwm.v
  /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/new/vga.v
  /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/new/main.v
}
add_files /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_0/design_1_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/constrs_1/new/mycontraint.xdc
set_property used_in_implementation false [get_files /home/fabrice/Documents/ethOverOfdm/modulationFm/modulationFm.srcs/constrs_1/new/mycontraint.xdc]

read_xdc /home/fabrice/Documents/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files /home/fabrice/Documents/Nexys-4-DDR-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
